table 'hospital_db patients'
	lineageTag: 2153f196-08aa-4e77-9ba0-a778bb4fe756

	measure 'Total Patients' = COUNTROWS('hospital_db patients')
		formatString: 0
		lineageTag: 650275e8-9392-44a9-913e-a4c189c0ddd1

	column patientID
		dataType: int64
		formatString: 0
		lineageTag: afc37a7c-f13f-4798-94c7-770ca974365e
		summarizeBy: none
		sourceColumn: patientID

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 8f161fd7-1902-423a-9748-09145b1ce057
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column dateOfBirth
		dataType: dateTime
		formatString: Long Date
		lineageTag: db6d25ad-f2bd-40e8-9f6d-272119fe9db3
		summarizeBy: none
		sourceColumn: dateOfBirth

		variation Variation
			isDefault
			relationship: 53031de7-1e88-4a20-81ff-668aecf86254
			defaultHierarchy: LocalDateTable_9c6a9d54-834c-4042-8574-048fb538383d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column gender
		dataType: string
		lineageTag: 255e8c8b-dc63-4174-85f2-75c17a1d5f0a
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: 8b6224f3-a6fe-411a-895f-f6039be87881
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	partition 'hospital_db patients' = m
		mode: import
		source =
				let
				    Source = MySQL.Database("localhost", "hospital_db", [ReturnSingleDatabase=true]),
				    hospital_db_patients = Source{[Schema="hospital_db",Item="patients"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(hospital_db_patients,{"hospital_db.appointments"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

